### ISSUE TITLE
Novas Features

### ISSUE THREAD

**Issue by valterpatrick** [luiis716/voltron#2]
Se possivel, adicione no readme possiveis novas features, isto se você concordar com elas.

* [SEM ESTADO] Criar uma rota para enviar o texto e retornar o audio, após isto ser apagado;
* [SEM ESTADO] Criar uma rota para enviar o texto e retornar o id do audio a ser gerado, assim como enviar o webhook que deve ser acionado assim que o audio for gerado para enviar o arquivo;

* Criar um serviço para apagar os audios que foram gerados e estão dentro do tempo configurado para serem apagados ou que foram gerados, mas por algum motivo não foram apagados conforme planejado;
* Criar um cadastro de usuario com senha e autenticação por token na api;
* Criar um painel administrativo web onde é possível visualizar os logs do servidor e definir configurações;
* No painel administrativo o usuário pode visualizar suas solicitações e baixar o arquivo caso ainda não esteja apagado;
* No painel administrativo o usuário pode definir configurações como tempo de vida do arquivo a ser gerado, webhook para enviar o arquivo após ser gerado e outras configurações;

* [USUÁRIO-SENHA-TOKEN] Criar uma rota para enviar o texto e retornar o audio, após isto ser apagado;
* [USUÁRIO-SENHA-TOKEN] Criar uma rota para enviar o texto e retornar o audio e seu respectivo id, mas sem ser apagado. Definir um tempo para ser apagado;
* [USUÁRIO-SENHA-TOKEN] Criar uma rota para enviar o texto e retornar o id do audio a ser gerado, não apagar o audio. Definir um tempo para ser apagado;
* [USUÁRIO-SENHA-TOKEN] Criar uma rota para buscar um audio a partir de um id gerado pela rota anterior;
* [USUÁRIO-SENHA-TOKEN] Criar uma rota para enviar o texto e retornar o id do audio a ser gerado, assim como enviar o webhook que deve ser acionado assim que o audio for gerado para enviar o arquivo;

**Comment by luiis716** [comment]
muito bom, gostei vou seguir alguma delas e vamos melhorando
